services:
- type: web
  name: minio
  env: docker
  dockerfilePath: ./Dockerfile
  dockerContext: .
  disk:
    name: data
    mountPath: /data
  envVars:
  - key: MINIO_UPLOAD_ACCESS_KEY
    generateValue: true
  - key: MINIO_UPLOAD_SECRET_KEY
    generateValue: true
